name: opencode

on:
  workflow_dispatch

jobs:
  opencode:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Run OpenCode
      uses: anomalyco/opencode/github@latest
      with:
        model: opencode/big-pickle
        prompt: |
          Check for library vulnerabilities
